### ISSUE TITLE
Is the code published somewhere?  

### ISSUE THREAD

**Issue by sagnik** [allenai/pdffigures2#1]
I am trying to add this code as a dependency in my project. Is it already published to a central repository?

**Comment by chrisc36** [comment]
Not at the moment, but it should be. I will take a look at publishing through maven.

**Comment by sagnik** [comment]
Thanks, I'm closing this then.

**Comment by chrisc36** [comment]
PDFFigures2 is now published at:
https://bintray.com/allenai/maven/pdffigures2

(see the README)

**Comment by mkapry** [comment]
> PDFFigures2 is now published at: https://bintray.com/allenai/maven/pdffigures2
> 
> (see the README)

The link is outdated, is there any other link?
