### ISSUE TITLE
Installation Steps

### ISSUE THREAD

**Issue by PatelKrutarth** [allenai/pdffigures2#16]
I have no experience with Scala, and very little with maven. So that I cannot be able to follow installation steps. I am using 64-bit Ubuntu 16.04. How can I install pdffigures2 on my machine?

**Comment by PatelKrutarth** [comment]
I used the command: $sbt compile
And I think it is working now. Please let me know if I have done something wrong, or I need to perform other steps to install.

**Comment by chrisc36** [comment]
Thats all you need to do, sbt will take care of everything else. The instructions from the "Command Line Tools" section of the README should work out of the box. (Maybe we should clarify this) the "Installation" section is just for using the library as a dependency.

**Comment by jenniferzhu** [comment]
@chrisc36 I have no background in Scala as well. Can you please provide some steps to download and install pdffigure2? I spent all day working with maven but nothing works yet...

**Comment by chrisc36** [comment]
We do not use maven, you need to install:

https://www.scala-sbt.org/1.0/docs/Setup.html

Then clone the repo and the "sbt" commands in the README should work.
