### ISSUE TITLE
Unresolved dependencies path and many Not Found error

### ISSUE THREAD

**Issue by JaniceXiong** [allenai/pdffigures2#42]
command is: sbt "runMain org.allenai.pdffigures2.FigureExtractorVisualizationCli sample.pdf"
sbt version is 1.3.0
![image](https://user-images.githubusercontent.com/43976565/122413680-2618f000-cfb9-11eb-8f5f-c60eb313af35.png)

**Comment by JaniceXiong** [comment]
I fixed it!
1. use this PR https://github.com/Sparkier/pdffigures2 and my sbt version change to 1.3.3! See here https://github.com/allenai/pdffigures2/issues/19
2. change the scala version to 2.11.11
![image](https://user-images.githubusercontent.com/43976565/122741501-97a5b680-d2b7-11eb-815d-20dddde929da.png)

**Comment by joshpoll** [comment]
switching the version to the `scala211` variable works for me as well
